source:      .
destination: ./_site
includes:    ./_includes
baseurl: ""

collections:
  projects:
    output: true 

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false